defaults:
  - task: adroit_hammer

name: train_Freqpolicy

task_name: ${task.name}
shape_meta: ${task.shape_meta}
exp_name: "debug"
ckpt_paths: ""
hf_repo_id: "HenryWJL/Freqpolicy"

# horizon: 4
horizon: 16
n_obs_steps: 2
# n_action_steps: 3
n_action_steps: 8
n_latency_steps: 0
dataset_obs_steps: ${n_obs_steps}
keypoint_visible_rate: 1.0
obs_as_global_cond: True

policy:
  _target_: diffusion_policy_3d.policy.Freqpolicy3d.Freqpolicy3d
  use_point_crop: true
  condition_type: film
  crop_shape:
  - 80
  - 80

  horizon: ${horizon}
  n_action_steps: ${n_action_steps}
  n_obs_steps: ${n_obs_steps}


  mask: True
  mask_ratio_min: 0.7
  diffloss_d: 3
  diffloss_w: 1024
  num_sampling_steps: 'ddim10'
  num_iter: 4
  cfg: 1
  point_feature_dim: 64
  state_mlp_size: 64
  encoder_embed_dim: 512
  decoder_embed_dim: ${policy.encoder_embed_dim}
  encoder_depth: 4
  decoder_depth: ${policy.encoder_depth}
  encoder_num_heads: 8
  decoder_num_heads: ${policy.encoder_num_heads}
  shape_meta: ${shape_meta}
  use_pc_color: false
  pointnet_type: "pointnet"
  temperature: 1.0
  obs_as_global_cond: true
  diffusion_batch_mul: 1



  pointcloud_encoder_cfg:
    in_channels: 3
    out_channels: ${policy.point_feature_dim}
    use_layernorm: true
    final_norm: layernorm # layernorm, none
    normal_channel: false


ema:
  _target_: diffusion_policy_3d.model.diffusion.ema_model.EMAModel
  update_after_step: 0
  inv_gamma: 1.0
  power: 0.75
  min_value: 0.0
  max_value: 0.9999

dataloader:
  batch_size: 128
  num_workers: 8
  shuffle: True
  pin_memory: True
  persistent_workers: False

val_dataloader:
  batch_size: 128
  num_workers: 8
  shuffle: False
  pin_memory: True
  persistent_workers: False

optimizer:
  _target_: torch.optim.AdamW
  lr: 1.0e-4
  betas: [0.95, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-6

training:
  device: "cuda:0"
  seed: 42
  debug: False
  resume: True
  lr_scheduler: cosine
  lr_warmup_steps: 500
  num_epochs: 3000
  gradient_accumulate_every: 1
  use_ema: True
  rollout_every: 200
  checkpoint_every: 200
  val_every: 1
  sample_every: 200
  max_train_steps: null
  max_val_steps: null
  tqdm_interval_sec: 1.0

logging:
  group: ${exp_name}
  id: null
  mode: online
  name: ${wandb_name}
  project: Freqpolicy
  resume: true
  tags:
  - Freqpolicy

checkpoint:
  save_ckpt: False # if True, save checkpoint every checkpoint_every
  topk:
    monitor_key: test_mean_score
    mode: max
    k: 1
    format_str: 'epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt'
  save_last_ckpt: True # this only saves when save_ckpt is True
  save_last_snapshot: False

multi_run:
  run_dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}
